# Change these first
owner: Thinking School # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Thinking School LMS
    url: https://lms.thinkingschool.vn
  - name: Thinking School Main Site
    url: https://thinkingschool.vn

